#!/bin/bash
Bin_Path="/usr/local/bin"
Betty_Style="betty-style"
Betty_Doc="betty-doc"
if["$#"= "0"]; then
echo "No arguments passed."
exit 1
fi
for argument in "$@" ; do
echo -e "/n========== $argument  =========="
${BIN_PATH}/${BETTY_STYLE} "$argument"
${BIN_PATH}/${BETTY_DOC} "$argument"
done
